# Generated by Django 5.2.12 on 2026-04-02 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
